"""
Load hierarchical courses into Redis.

This script loads courses generated by generate_hierarchical_courses.py
into the two-tier Redis storage (summaries + details).
"""

import asyncio
import json
import click
from pathlib import Path
from datetime import datetime

from redis_context_course.hierarchical_models import (
    CourseSummary,
    CourseDetails,
    HierarchicalCourse,
)
from redis_context_course.hierarchical_manager import HierarchicalCourseManager


async def load_courses_from_json(json_file: Path, manager: HierarchicalCourseManager):
    """Load courses from JSON file into Redis."""
    
    print(f"📖 Loading courses from {json_file}...")
    
    with open(json_file, 'r') as f:
        data = json.load(f)
    
    courses_data = data.get("courses", [])
    print(f"Found {len(courses_data)} courses in file")
    
    loaded = 0
    failed = 0
    
    for course_data in courses_data:
        try:
            # Reconstruct HierarchicalCourse
            summary = CourseSummary(**course_data["summary"])
            details = CourseDetails(**course_data["details"])
            
            course = HierarchicalCourse(
                id=course_data["id"],
                summary=summary,
                details=details,
                created_at=datetime.fromisoformat(course_data["created_at"]),
            )
            
            # Add to Redis
            success = await manager.add_course(course)
            if success:
                loaded += 1
                if loaded % 10 == 0:
                    print(f"  Loaded {loaded}/{len(courses_data)} courses...")
            else:
                failed += 1
                
        except Exception as e:
            print(f"  ❌ Error loading course: {e}")
            failed += 1
    
    print(f"\n✅ Loading complete!")
    print(f"   Loaded: {loaded}")
    print(f"   Failed: {failed}")
    
    return loaded, failed


@click.command()
@click.option(
    '--input-file',
    '-i',
    type=click.Path(exists=True),
    required=True,
    help='JSON file with hierarchical courses'
)
@click.option(
    '--summary-index',
    '-s',
    default='course_summaries',
    help='Name for summary vector index'
)
@click.option(
    '--details-prefix',
    '-d',
    default='course_details',
    help='Prefix for details hash keys'
)
def main(input_file: str, summary_index: str, details_prefix: str):
    """Load hierarchical courses into Redis."""
    
    print("🚀 Hierarchical Course Loader\n")
    
    # Create manager
    manager = HierarchicalCourseManager(
        summary_index_name=summary_index,
        details_prefix=details_prefix,
    )
    
    # Load courses
    input_path = Path(input_file)
    loaded, failed = asyncio.run(load_courses_from_json(input_path, manager))
    
    if loaded > 0:
        print(f"\n📊 Redis Storage:")
        print(f"   Summary index: {summary_index}")
        print(f"   Details prefix: {details_prefix}")
        print(f"\n💡 You can now use HierarchicalCourseManager to search courses!")


if __name__ == "__main__":
    main()

