services:
  redis:
    image: redis:8.2.1
    container_name: redis-context-engineering
    ports:
      - "6379:6379"
    environment:
      - REDIS_ARGS=--save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  agent-memory-server:
    image: ghcr.io/redis/agent-memory-server:0.12.3
    container_name: agent-memory-server
    command: ["agent-memory", "api", "--host", "0.0.0.0", "--port", "8000", "--no-worker"]
    ports:
      - "8088:8000"  # Host port changed to avoid conflicts
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  redis-data:

